### PR TITLE
Feat: Added `use_host_network` param to `get_source()`, for Docker containers to use host's network

### PR DESCRIPTION
**Pull request by niyasrad**
### What

Adding the `use_host_network` param so that the `DockerExecutor` can run the containers with access to host's network.

### Why

I've been excited ever since the announcement of the `DockerExecutor` experimental feature, since i wanted to run all the **Java connectors** and test them out when i have time.

I started out with **PostgreSQL**. I gave it my local postgres configuration and also tried the PUBLIC RNA postgres. But it failed to connect, and gave me the following error:

```
airbyte.exceptions.AirbyteConnectorCheckFailedError: AirbyteConnectorCheckFailedError: Connector check failed.
    Failure Reason: 'Message: HikariPool-1 - Connection is not available, request timed out after 10002ms (total=0, active=0, idle=0, waiting=0)'
More info: https://docs.airbyte.com/integrations/sources/postgres
```

I made a change over the `get_source()` function and it worked flawlessly afterwards.

### How

- Added a `use_host_network` in `get_source()` as a parameter to control whether the Docker container should use the host network.
- Updated the `DockerExecutor` configuration to conditionally include the `--network host` option in the Docker run command.

## Summary by CodeRabbit

- **New Features**
	- Introduced an option to run connectors using the host network for accessing local resources, enhancing connectivity for specific use cases.

### CODE REVIEW

**Review by aaronsteers — APPROVED** [review]
This looks great, @niyasrad! 

Thank you for this contribution. Any reason we should not merge as-is (assuming tests and lint checks pass)? 

Since you already adding the description to the docstring, related docs will be updated automatically. 🙏

**Comment by aaronsteers** [comment]
@coderabbitai review

**Comment by niyasrad** [comment]
> Thank you for this contribution. Any reason we should not merge as-is (assuming tests and lint checks pass)? 


@aaronsteers 
I have tested the use-cases, and all conditions with the code that I have submitted. 

You can merge as-is, and update the experimental version! I'm excited to use it further 😆

**Comment by aaronsteers** [comment]
Tests passing! Ready to merge! Thanks @niyasrad, for this contribution!

**Review by aaronsteers — APPROVED** [review]
Looks great! ✅

**Pull request merged**
